name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: False
      matrix:
        os: [ubuntu-latest]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Checkout submodules
      uses: textbook/git-checkout-submodule-action@master
      with:
        remote: true

    - uses: actions/setup-python@v2
      name: Install Python
      with:
        python-version: '3.8'

    - name: Install cibuildwheel
      run: |
        python -m pip install cibuildwheel==1.8.0

    - name: Set up QEMU
      if: runner.os == 'Linux'
      uses: docker/setup-qemu-action@v1
      with:
        platforms: arm64

    - name: Build wheels
      run: |
        python -m cibuildwheel --output-dir dist
      env:
        # build python 3.7 and 3.8
        CIBW_BUILD: cp37-* cp38-* cp39-*
        CIBW_BEFORE_ALL: >
          python -m pip install --upgrade pip &&
          python -m pip install --upgrade cffi
        CIBW_ARCHS_LINUX: x86_64 aarch64
        CIBW_TEST_REQUIRES: tox
#        CIBW_BEFORE_ALL_LINUX: >

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: wheels
        path: dist
